spring.application.name=notes-knowledge-workspace
spring.modulith.detection-strategy=explicitly-annotated

logging.structured.format.console=ecs
logging.structured.ecs.service.name=${spring.application.name}
logging.structured.ecs.service.environment=${APP_ENVIRONMENT:local}
logging.structured.ecs.service.version=${APP_VERSION:0.0.1-SNAPSHOT}

management.endpoints.web.exposure.include=health
management.endpoints.jmx.exposure.exclude=*
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

server.error.include-message=never
server.error.include-stacktrace=never
