spring.application.name=notes-knowledge-workspace
spring.modulith.detection-strategy=explicitly-annotated
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=identity.spring_session
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/
spring.jackson.deserialization.fail-on-unknown-properties=true

logging.structured.format.console=ecs
logging.structured.ecs.service.name=${spring.application.name}
logging.structured.ecs.service.environment=${APP_ENVIRONMENT:local}
logging.structured.ecs.service.version=${APP_VERSION:0.0.1-SNAPSHOT}

management.endpoints.web.exposure.include=health
management.endpoints.jmx.exposure.exclude=*
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

server.error.include-message=never
server.error.include-stacktrace=never
